### ISSUE TITLE
Proje geliştirilmeye neden devam etmiyor?

### ISSUE THREAD

**Issue by beucismis** [abdllhygt/coz#1]
@abdllhygt zamanında Discord'da bu dil sayesinde tanışmıştık senle. Bana son sürümlerini test ettirdiğini hatırlıyorum. Gerek Türkçe sözdizimiyle gerekse o zamana kadar duymadığım bir dille bunu yapıyor olman hayli ilgimi çekmişti. Sonrasında aradan 1 yıldan fazla bir zaman geçti. Neden hala geliştirme sürecine devam etmiyorsun merak ettim.

**Comment by abdllhygt** [comment]
Kusura bakma baya geç cevaplıyorum, geliştirmeye yeniden başladım. Teşekkür ederim ilgin için.

**Comment by beucismis** [comment]
Sorun değil. Yeniden başlamana sevindim. Takipteyim. Versiyonları "Releases" kısmında "Changelog"larla beraber yayımlarsan iyi olur.

**Comment by abdllhygt** [comment]
Teşekkür ederim
